// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/LockService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_LockService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_LockService_proto_rawDescGZIP(), []int{0}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_LockService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_LockService_proto_rawDescGZIP(), []int{1}
}

type AcquireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_proto_LockService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_proto_LockService_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *AcquireRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AcquireRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type AcquireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResponse) Reset() {
	*x = AcquireResponse{}
	mi := &file_proto_LockService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResponse) ProtoMessage() {}

func (x *AcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireResponse.ProtoReflect.Descriptor instead.
func (*AcquireResponse) Descriptor() ([]byte, []int) {
	return file_proto_LockService_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_LockService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_LockService_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *ReleaseRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ReleaseRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_proto_LockService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_LockService_proto_rawDescGZIP(), []int{5}
}

var File_proto_LockService_proto protoreflect.FileDescriptor

const file_proto_LockService_proto_rawDesc = "" +
	"\n" +
	"\x17proto/LockService.proto\x12\bdfs.lock\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"^\n" +
	"\x0eAcquireRequest\x12\x16\n" +
	"\x06lockId\x18\x01 \x01(\tR\x06lockId\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\tR\aownerId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\"<\n" +
	"\x0fAcquireResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01B\n" +
	"\n" +
	"\b_success\"^\n" +
	"\x0eReleaseRequest\x12\x16\n" +
	"\x06lockId\x18\x01 \x01(\tR\x06lockId\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\tR\aownerId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\"\x11\n" +
	"\x0fReleaseResponse2\xc4\x01\n" +
	"\vLockService\x125\n" +
	"\x04stop\x12\x15.dfs.lock.StopRequest\x1a\x16.dfs.lock.StopResponse\x12>\n" +
	"\aacquire\x12\x18.dfs.lock.AcquireRequest\x1a\x19.dfs.lock.AcquireResponse\x12>\n" +
	"\arelease\x12\x18.dfs.lock.ReleaseRequest\x1a\x19.dfs.lock.ReleaseResponseb\x06proto3"

var (
	file_proto_LockService_proto_rawDescOnce sync.Once
	file_proto_LockService_proto_rawDescData []byte
)

func file_proto_LockService_proto_rawDescGZIP() []byte {
	file_proto_LockService_proto_rawDescOnce.Do(func() {
		file_proto_LockService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_LockService_proto_rawDesc), len(file_proto_LockService_proto_rawDesc)))
	})
	return file_proto_LockService_proto_rawDescData
}

var file_proto_LockService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_LockService_proto_goTypes = []any{
	(*StopRequest)(nil),     // 0: dfs.lock.StopRequest
	(*StopResponse)(nil),    // 1: dfs.lock.StopResponse
	(*AcquireRequest)(nil),  // 2: dfs.lock.AcquireRequest
	(*AcquireResponse)(nil), // 3: dfs.lock.AcquireResponse
	(*ReleaseRequest)(nil),  // 4: dfs.lock.ReleaseRequest
	(*ReleaseResponse)(nil), // 5: dfs.lock.ReleaseResponse
}
var file_proto_LockService_proto_depIdxs = []int32{
	0, // 0: dfs.lock.LockService.stop:input_type -> dfs.lock.StopRequest
	2, // 1: dfs.lock.LockService.acquire:input_type -> dfs.lock.AcquireRequest
	4, // 2: dfs.lock.LockService.release:input_type -> dfs.lock.ReleaseRequest
	1, // 3: dfs.lock.LockService.stop:output_type -> dfs.lock.StopResponse
	3, // 4: dfs.lock.LockService.acquire:output_type -> dfs.lock.AcquireResponse
	5, // 5: dfs.lock.LockService.release:output_type -> dfs.lock.ReleaseResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_LockService_proto_init() }
func file_proto_LockService_proto_init() {
	if File_proto_LockService_proto != nil {
		return
	}
	file_proto_LockService_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_LockService_proto_rawDesc), len(file_proto_LockService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_LockService_proto_goTypes,
		DependencyIndexes: file_proto_LockService_proto_depIdxs,
		MessageInfos:      file_proto_LockService_proto_msgTypes,
	}.Build()
	File_proto_LockService_proto = out.File
	file_proto_LockService_proto_goTypes = nil
	file_proto_LockService_proto_depIdxs = nil
}
