// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/lock.proto

package lock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcquireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_proto_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_proto_lock_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type AcquireReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireReply) Reset() {
	*x = AcquireReply{}
	mi := &file_proto_lock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireReply) ProtoMessage() {}

func (x *AcquireReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireReply.ProtoReflect.Descriptor instead.
func (*AcquireReply) Descriptor() ([]byte, []int) {
	return file_proto_lock_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireReply) GetResult() *wrapperspb.BoolValue {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_lock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_lock_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type ReleaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReply) Reset() {
	*x = ReleaseReply{}
	mi := &file_proto_lock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReply) ProtoMessage() {}

func (x *ReleaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReply.ProtoReflect.Descriptor instead.
func (*ReleaseReply) Descriptor() ([]byte, []int) {
	return file_proto_lock_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseReply) GetResult() *wrapperspb.BoolValue {
	if x != nil {
		return x.Result
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_lock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_lock_proto_rawDescGZIP(), []int{4}
}

type StopReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReply) Reset() {
	*x = StopReply{}
	mi := &file_proto_lock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReply) ProtoMessage() {}

func (x *StopReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReply.ProtoReflect.Descriptor instead.
func (*StopReply) Descriptor() ([]byte, []int) {
	return file_proto_lock_proto_rawDescGZIP(), []int{5}
}

func (x *StopReply) GetResult() *wrapperspb.BoolValue {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_lock_proto protoreflect.FileDescriptor

const file_proto_lock_proto_rawDesc = "" +
	"\n" +
	"\x10proto/lock.proto\x12\x04lock\x1a\x1egoogle/protobuf/wrappers.proto\"(\n" +
	"\x0eAcquireRequest\x12\x16\n" +
	"\x06lockId\x18\x01 \x01(\tR\x06lockId\"B\n" +
	"\fAcquireReply\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x06result\"(\n" +
	"\x0eReleaseRequest\x12\x16\n" +
	"\x06lockId\x18\x01 \x01(\tR\x06lockId\"B\n" +
	"\fReleaseReply\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x06result\"\r\n" +
	"\vStopRequest\"?\n" +
	"\tStopReply\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x06result2\x9c\x01\n" +
	"\x04Lock\x123\n" +
	"\aAcquire\x12\x14.lock.AcquireRequest\x1a\x12.lock.AcquireReply\x123\n" +
	"\aRelease\x12\x14.lock.ReleaseRequest\x1a\x12.lock.ReleaseReply\x12*\n" +
	"\x04Stop\x12\x11.lock.StopRequest\x1a\x0f.lock.StopReplyB\x15Z\x13proto-gen/lock;lockb\x06proto3"

var (
	file_proto_lock_proto_rawDescOnce sync.Once
	file_proto_lock_proto_rawDescData []byte
)

func file_proto_lock_proto_rawDescGZIP() []byte {
	file_proto_lock_proto_rawDescOnce.Do(func() {
		file_proto_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lock_proto_rawDesc), len(file_proto_lock_proto_rawDesc)))
	})
	return file_proto_lock_proto_rawDescData
}

var file_proto_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_lock_proto_goTypes = []any{
	(*AcquireRequest)(nil),       // 0: lock.AcquireRequest
	(*AcquireReply)(nil),         // 1: lock.AcquireReply
	(*ReleaseRequest)(nil),       // 2: lock.ReleaseRequest
	(*ReleaseReply)(nil),         // 3: lock.ReleaseReply
	(*StopRequest)(nil),          // 4: lock.StopRequest
	(*StopReply)(nil),            // 5: lock.StopReply
	(*wrapperspb.BoolValue)(nil), // 6: google.protobuf.BoolValue
}
var file_proto_lock_proto_depIdxs = []int32{
	6, // 0: lock.AcquireReply.result:type_name -> google.protobuf.BoolValue
	6, // 1: lock.ReleaseReply.result:type_name -> google.protobuf.BoolValue
	6, // 2: lock.StopReply.result:type_name -> google.protobuf.BoolValue
	0, // 3: lock.Lock.Acquire:input_type -> lock.AcquireRequest
	2, // 4: lock.Lock.Release:input_type -> lock.ReleaseRequest
	4, // 5: lock.Lock.Stop:input_type -> lock.StopRequest
	1, // 6: lock.Lock.Acquire:output_type -> lock.AcquireReply
	3, // 7: lock.Lock.Release:output_type -> lock.ReleaseReply
	5, // 8: lock.Lock.Stop:output_type -> lock.StopReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_lock_proto_init() }
func file_proto_lock_proto_init() {
	if File_proto_lock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lock_proto_rawDesc), len(file_proto_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lock_proto_goTypes,
		DependencyIndexes: file_proto_lock_proto_depIdxs,
		MessageInfos:      file_proto_lock_proto_msgTypes,
	}.Build()
	File_proto_lock_proto = out.File
	file_proto_lock_proto_goTypes = nil
	file_proto_lock_proto_depIdxs = nil
}
