// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/PaxosService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        int64                  `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	N             int64                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_proto_PaxosService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PaxosService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_PaxosService_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetViewId() int64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *PrepareRequest) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsOld         bool                   `protobuf:"varint,2,opt,name=isOld,proto3" json:"isOld,omitempty"`
	ViewId        int64                  `protobuf:"varint,3,opt,name=viewId,proto3" json:"viewId,omitempty"`
	View          []string               `protobuf:"bytes,4,rep,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_proto_PaxosService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PaxosService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_proto_PaxosService_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareResponse) GetIsOld() bool {
	if x != nil {
		return x.IsOld
	}
	return false
}

func (x *PrepareResponse) GetViewId() int64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *PrepareResponse) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	View          []string               `protobuf:"bytes,2,rep,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_proto_PaxosService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PaxosService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_proto_PaxosService_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *AcceptRequest) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_proto_PaxosService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PaxosService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_proto_PaxosService_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        int64                  `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	View          []string               `protobuf:"bytes,2,rep,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_proto_PaxosService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PaxosService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_proto_PaxosService_proto_rawDescGZIP(), []int{4}
}

func (x *DecideRequest) GetViewId() int64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *DecideRequest) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

type DecideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_proto_PaxosService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PaxosService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_proto_PaxosService_proto_rawDescGZIP(), []int{5}
}

var File_proto_PaxosService_proto protoreflect.FileDescriptor

const file_proto_PaxosService_proto_rawDesc = "" +
	"\n" +
	"\x18proto/PaxosService.proto\x12\vdfs.replica\"6\n" +
	"\x0ePrepareRequest\x12\x16\n" +
	"\x06viewId\x18\x01 \x01(\x03R\x06viewId\x12\f\n" +
	"\x01n\x18\x02 \x01(\x03R\x01n\"m\n" +
	"\x0fPrepareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05isOld\x18\x02 \x01(\bR\x05isOld\x12\x16\n" +
	"\x06viewId\x18\x03 \x01(\x03R\x06viewId\x12\x12\n" +
	"\x04view\x18\x04 \x03(\tR\x04view\"1\n" +
	"\rAcceptRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x03R\x01n\x12\x12\n" +
	"\x04view\x18\x02 \x03(\tR\x04view\"*\n" +
	"\x0eAcceptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\rDecideRequest\x12\x16\n" +
	"\x06viewId\x18\x01 \x01(\x03R\x06viewId\x12\x12\n" +
	"\x04view\x18\x02 \x03(\tR\x04view\"\x10\n" +
	"\x0eDecideResponse2\xda\x01\n" +
	"\fPaxosService\x12D\n" +
	"\aprepare\x12\x1b.dfs.replica.PrepareRequest\x1a\x1c.dfs.replica.PrepareResponse\x12A\n" +
	"\x06accept\x12\x1a.dfs.replica.AcceptRequest\x1a\x1b.dfs.replica.AcceptResponse\x12A\n" +
	"\x06decide\x12\x1a.dfs.replica.DecideRequest\x1a\x1b.dfs.replica.DecideResponseb\x06proto3"

var (
	file_proto_PaxosService_proto_rawDescOnce sync.Once
	file_proto_PaxosService_proto_rawDescData []byte
)

func file_proto_PaxosService_proto_rawDescGZIP() []byte {
	file_proto_PaxosService_proto_rawDescOnce.Do(func() {
		file_proto_PaxosService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_PaxosService_proto_rawDesc), len(file_proto_PaxosService_proto_rawDesc)))
	})
	return file_proto_PaxosService_proto_rawDescData
}

var file_proto_PaxosService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_PaxosService_proto_goTypes = []any{
	(*PrepareRequest)(nil),  // 0: dfs.replica.PrepareRequest
	(*PrepareResponse)(nil), // 1: dfs.replica.PrepareResponse
	(*AcceptRequest)(nil),   // 2: dfs.replica.AcceptRequest
	(*AcceptResponse)(nil),  // 3: dfs.replica.AcceptResponse
	(*DecideRequest)(nil),   // 4: dfs.replica.DecideRequest
	(*DecideResponse)(nil),  // 5: dfs.replica.DecideResponse
}
var file_proto_PaxosService_proto_depIdxs = []int32{
	0, // 0: dfs.replica.PaxosService.prepare:input_type -> dfs.replica.PrepareRequest
	2, // 1: dfs.replica.PaxosService.accept:input_type -> dfs.replica.AcceptRequest
	4, // 2: dfs.replica.PaxosService.decide:input_type -> dfs.replica.DecideRequest
	1, // 3: dfs.replica.PaxosService.prepare:output_type -> dfs.replica.PrepareResponse
	3, // 4: dfs.replica.PaxosService.accept:output_type -> dfs.replica.AcceptResponse
	5, // 5: dfs.replica.PaxosService.decide:output_type -> dfs.replica.DecideResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_PaxosService_proto_init() }
func file_proto_PaxosService_proto_init() {
	if File_proto_PaxosService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_PaxosService_proto_rawDesc), len(file_proto_PaxosService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_PaxosService_proto_goTypes,
		DependencyIndexes: file_proto_PaxosService_proto_depIdxs,
		MessageInfos:      file_proto_PaxosService_proto_msgTypes,
	}.Build()
	File_proto_PaxosService_proto = out.File
	file_proto_PaxosService_proto_goTypes = nil
	file_proto_PaxosService_proto_depIdxs = nil
}
