// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/ManagementService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_ManagementService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ManagementService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ManagementService_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_ManagementService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ManagementService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_ManagementService_proto_rawDescGZIP(), []int{1}
}

var File_proto_ManagementService_proto protoreflect.FileDescriptor

const file_proto_ManagementService_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/ManagementService.proto\x12\vdfs.replica\"*\n" +
	"\x10HeartbeatRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\"\x13\n" +
	"\x11HeartbeatResponse2_\n" +
	"\x11ManagementService\x12J\n" +
	"\theartbeat\x12\x1d.dfs.replica.HeartbeatRequest\x1a\x1e.dfs.replica.HeartbeatResponseb\x06proto3"

var (
	file_proto_ManagementService_proto_rawDescOnce sync.Once
	file_proto_ManagementService_proto_rawDescData []byte
)

func file_proto_ManagementService_proto_rawDescGZIP() []byte {
	file_proto_ManagementService_proto_rawDescOnce.Do(func() {
		file_proto_ManagementService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ManagementService_proto_rawDesc), len(file_proto_ManagementService_proto_rawDesc)))
	})
	return file_proto_ManagementService_proto_rawDescData
}

var file_proto_ManagementService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ManagementService_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: dfs.replica.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: dfs.replica.HeartbeatResponse
}
var file_proto_ManagementService_proto_depIdxs = []int32{
	0, // 0: dfs.replica.ManagementService.heartbeat:input_type -> dfs.replica.HeartbeatRequest
	1, // 1: dfs.replica.ManagementService.heartbeat:output_type -> dfs.replica.HeartbeatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ManagementService_proto_init() }
func file_proto_ManagementService_proto_init() {
	if File_proto_ManagementService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ManagementService_proto_rawDesc), len(file_proto_ManagementService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ManagementService_proto_goTypes,
		DependencyIndexes: file_proto_ManagementService_proto_depIdxs,
		MessageInfos:      file_proto_ManagementService_proto_msgTypes,
	}.Build()
	File_proto_ManagementService_proto = out.File
	file_proto_ManagementService_proto_goTypes = nil
	file_proto_ManagementService_proto_depIdxs = nil
}
