// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/LockCacheService.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LockCacheService_Revoke_FullMethodName = "/dfs.dfs.LockCacheService/revoke"
	LockCacheService_Retry_FullMethodName  = "/dfs.dfs.LockCacheService/retry"
)

// LockCacheServiceClient is the client API for LockCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LockCacheServiceClient interface {
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
	Retry(ctx context.Context, in *RetryRequest, opts ...grpc.CallOption) (*RetryResponse, error)
}

type lockCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLockCacheServiceClient(cc grpc.ClientConnInterface) LockCacheServiceClient {
	return &lockCacheServiceClient{cc}
}

func (c *lockCacheServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, LockCacheService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockCacheServiceClient) Retry(ctx context.Context, in *RetryRequest, opts ...grpc.CallOption) (*RetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryResponse)
	err := c.cc.Invoke(ctx, LockCacheService_Retry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockCacheServiceServer is the server API for LockCacheService service.
// All implementations must embed UnimplementedLockCacheServiceServer
// for forward compatibility.
type LockCacheServiceServer interface {
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	Retry(context.Context, *RetryRequest) (*RetryResponse, error)
	mustEmbedUnimplementedLockCacheServiceServer()
}

// UnimplementedLockCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLockCacheServiceServer struct{}

func (UnimplementedLockCacheServiceServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedLockCacheServiceServer) Retry(context.Context, *RetryRequest) (*RetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retry not implemented")
}
func (UnimplementedLockCacheServiceServer) mustEmbedUnimplementedLockCacheServiceServer() {}
func (UnimplementedLockCacheServiceServer) testEmbeddedByValue()                          {}

// UnsafeLockCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockCacheServiceServer will
// result in compilation errors.
type UnsafeLockCacheServiceServer interface {
	mustEmbedUnimplementedLockCacheServiceServer()
}

func RegisterLockCacheServiceServer(s grpc.ServiceRegistrar, srv LockCacheServiceServer) {
	// If the following call pancis, it indicates UnimplementedLockCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LockCacheService_ServiceDesc, srv)
}

func _LockCacheService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockCacheServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockCacheService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockCacheServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockCacheService_Retry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockCacheServiceServer).Retry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockCacheService_Retry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockCacheServiceServer).Retry(ctx, req.(*RetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockCacheService_ServiceDesc is the grpc.ServiceDesc for LockCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.dfs.LockCacheService",
	HandlerType: (*LockCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "revoke",
			Handler:    _LockCacheService_Revoke_Handler,
		},
		{
			MethodName: "retry",
			Handler:    _LockCacheService_Retry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/LockCacheService.proto",
}
