// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/LockCacheService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_proto_LockCacheService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockCacheService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_LockCacheService_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_proto_LockCacheService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockCacheService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_LockCacheService_proto_rawDescGZIP(), []int{1}
}

type RetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRequest) Reset() {
	*x = RetryRequest{}
	mi := &file_proto_LockCacheService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRequest) ProtoMessage() {}

func (x *RetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockCacheService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRequest.ProtoReflect.Descriptor instead.
func (*RetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_LockCacheService_proto_rawDescGZIP(), []int{2}
}

func (x *RetryRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *RetryRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type RetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryResponse) Reset() {
	*x = RetryResponse{}
	mi := &file_proto_LockCacheService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryResponse) ProtoMessage() {}

func (x *RetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LockCacheService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryResponse.ProtoReflect.Descriptor instead.
func (*RetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_LockCacheService_proto_rawDescGZIP(), []int{3}
}

var File_proto_LockCacheService_proto protoreflect.FileDescriptor

const file_proto_LockCacheService_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/LockCacheService.proto\x12\adfs.dfs\"'\n" +
	"\rRevokeRequest\x12\x16\n" +
	"\x06lockId\x18\x01 \x01(\tR\x06lockId\"\x10\n" +
	"\x0eRevokeResponse\"B\n" +
	"\fRetryRequest\x12\x16\n" +
	"\x06lockId\x18\x01 \x01(\tR\x06lockId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\"\x0f\n" +
	"\rRetryResponse2\x85\x01\n" +
	"\x10LockCacheService\x129\n" +
	"\x06revoke\x12\x16.dfs.dfs.RevokeRequest\x1a\x17.dfs.dfs.RevokeResponse\x126\n" +
	"\x05retry\x12\x15.dfs.dfs.RetryRequest\x1a\x16.dfs.dfs.RetryResponseb\x06proto3"

var (
	file_proto_LockCacheService_proto_rawDescOnce sync.Once
	file_proto_LockCacheService_proto_rawDescData []byte
)

func file_proto_LockCacheService_proto_rawDescGZIP() []byte {
	file_proto_LockCacheService_proto_rawDescOnce.Do(func() {
		file_proto_LockCacheService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_LockCacheService_proto_rawDesc), len(file_proto_LockCacheService_proto_rawDesc)))
	})
	return file_proto_LockCacheService_proto_rawDescData
}

var file_proto_LockCacheService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_LockCacheService_proto_goTypes = []any{
	(*RevokeRequest)(nil),  // 0: dfs.dfs.RevokeRequest
	(*RevokeResponse)(nil), // 1: dfs.dfs.RevokeResponse
	(*RetryRequest)(nil),   // 2: dfs.dfs.RetryRequest
	(*RetryResponse)(nil),  // 3: dfs.dfs.RetryResponse
}
var file_proto_LockCacheService_proto_depIdxs = []int32{
	0, // 0: dfs.dfs.LockCacheService.revoke:input_type -> dfs.dfs.RevokeRequest
	2, // 1: dfs.dfs.LockCacheService.retry:input_type -> dfs.dfs.RetryRequest
	1, // 2: dfs.dfs.LockCacheService.revoke:output_type -> dfs.dfs.RevokeResponse
	3, // 3: dfs.dfs.LockCacheService.retry:output_type -> dfs.dfs.RetryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_LockCacheService_proto_init() }
func file_proto_LockCacheService_proto_init() {
	if File_proto_LockCacheService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_LockCacheService_proto_rawDesc), len(file_proto_LockCacheService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_LockCacheService_proto_goTypes,
		DependencyIndexes: file_proto_LockCacheService_proto_depIdxs,
		MessageInfos:      file_proto_LockCacheService_proto_msgTypes,
	}.Build()
	File_proto_LockCacheService_proto = out.File
	file_proto_LockCacheService_proto_goTypes = nil
	file_proto_LockCacheService_proto_depIdxs = nil
}
