// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/DfsService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{0}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{1}
}

type DirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryName string                 `protobuf:"bytes,1,opt,name=directoryName,proto3" json:"directoryName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirRequest) Reset() {
	*x = DirRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirRequest) ProtoMessage() {}

func (x *DirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirRequest.ProtoReflect.Descriptor instead.
func (*DirRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{2}
}

func (x *DirRequest) GetDirectoryName() string {
	if x != nil {
		return x.DirectoryName
	}
	return ""
}

type DirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	DirList       []string               `protobuf:"bytes,2,rep,name=dirList,proto3" json:"dirList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirResponse) Reset() {
	*x = DirResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirResponse) ProtoMessage() {}

func (x *DirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirResponse.ProtoReflect.Descriptor instead.
func (*DirResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{3}
}

func (x *DirResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *DirResponse) GetDirList() []string {
	if x != nil {
		return x.DirList
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryName string                 `protobuf:"bytes,1,opt,name=directoryName,proto3" json:"directoryName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{4}
}

func (x *MkdirRequest) GetDirectoryName() string {
	if x != nil {
		return x.DirectoryName
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{5}
}

func (x *MkdirResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type RmdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryName string                 `protobuf:"bytes,1,opt,name=directoryName,proto3" json:"directoryName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirRequest) Reset() {
	*x = RmdirRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirRequest) ProtoMessage() {}

func (x *RmdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirRequest.ProtoReflect.Descriptor instead.
func (*RmdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{6}
}

func (x *RmdirRequest) GetDirectoryName() string {
	if x != nil {
		return x.DirectoryName
	}
	return ""
}

type RmdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirResponse) Reset() {
	*x = RmdirResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirResponse) ProtoMessage() {}

func (x *RmdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirResponse.ProtoReflect.Descriptor instead.
func (*RmdirResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{7}
}

func (x *RmdirResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{8}
}

func (x *GetRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=fileData,proto3,oneof" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{9}
}

func (x *GetResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=fileData,proto3,oneof" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{10}
}

func (x *PutRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PutRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{11}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_DfsService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_DfsService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DfsService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_DfsService_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

var File_proto_DfsService_proto protoreflect.FileDescriptor

const file_proto_DfsService_proto_rawDesc = "" +
	"\n" +
	"\x16proto/DfsService.proto\x12\adfs.dfs\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"2\n" +
	"\n" +
	"DirRequest\x12$\n" +
	"\rdirectoryName\x18\x01 \x01(\tR\rdirectoryName\"R\n" +
	"\vDirResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01\x12\x18\n" +
	"\adirList\x18\x02 \x03(\tR\adirListB\n" +
	"\n" +
	"\b_success\"4\n" +
	"\fMkdirRequest\x12$\n" +
	"\rdirectoryName\x18\x01 \x01(\tR\rdirectoryName\":\n" +
	"\rMkdirResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01B\n" +
	"\n" +
	"\b_success\"4\n" +
	"\fRmdirRequest\x12$\n" +
	"\rdirectoryName\x18\x01 \x01(\tR\rdirectoryName\":\n" +
	"\rRmdirResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01B\n" +
	"\n" +
	"\b_success\"(\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\";\n" +
	"\vGetResponse\x12\x1f\n" +
	"\bfileData\x18\x01 \x01(\fH\x00R\bfileData\x88\x01\x01B\v\n" +
	"\t_fileData\"V\n" +
	"\n" +
	"PutRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\bfileData\x18\x02 \x01(\fH\x00R\bfileData\x88\x01\x01B\v\n" +
	"\t_fileData\"8\n" +
	"\vPutResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01B\n" +
	"\n" +
	"\b_success\"+\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\";\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01B\n" +
	"\n" +
	"\b_success2\x82\x03\n" +
	"\n" +
	"DfsService\x123\n" +
	"\x04stop\x12\x14.dfs.dfs.StopRequest\x1a\x15.dfs.dfs.StopResponse\x120\n" +
	"\x03dir\x12\x13.dfs.dfs.DirRequest\x1a\x14.dfs.dfs.DirResponse\x126\n" +
	"\x05mkdir\x12\x15.dfs.dfs.MkdirRequest\x1a\x16.dfs.dfs.MkdirResponse\x126\n" +
	"\x05rmdir\x12\x15.dfs.dfs.RmdirRequest\x1a\x16.dfs.dfs.RmdirResponse\x120\n" +
	"\x03get\x12\x13.dfs.dfs.GetRequest\x1a\x14.dfs.dfs.GetResponse\x120\n" +
	"\x03put\x12\x13.dfs.dfs.PutRequest\x1a\x14.dfs.dfs.PutResponse\x129\n" +
	"\x06delete\x12\x16.dfs.dfs.DeleteRequest\x1a\x17.dfs.dfs.DeleteResponseb\x06proto3"

var (
	file_proto_DfsService_proto_rawDescOnce sync.Once
	file_proto_DfsService_proto_rawDescData []byte
)

func file_proto_DfsService_proto_rawDescGZIP() []byte {
	file_proto_DfsService_proto_rawDescOnce.Do(func() {
		file_proto_DfsService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_DfsService_proto_rawDesc), len(file_proto_DfsService_proto_rawDesc)))
	})
	return file_proto_DfsService_proto_rawDescData
}

var file_proto_DfsService_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_DfsService_proto_goTypes = []any{
	(*StopRequest)(nil),    // 0: dfs.dfs.StopRequest
	(*StopResponse)(nil),   // 1: dfs.dfs.StopResponse
	(*DirRequest)(nil),     // 2: dfs.dfs.DirRequest
	(*DirResponse)(nil),    // 3: dfs.dfs.DirResponse
	(*MkdirRequest)(nil),   // 4: dfs.dfs.MkdirRequest
	(*MkdirResponse)(nil),  // 5: dfs.dfs.MkdirResponse
	(*RmdirRequest)(nil),   // 6: dfs.dfs.RmdirRequest
	(*RmdirResponse)(nil),  // 7: dfs.dfs.RmdirResponse
	(*GetRequest)(nil),     // 8: dfs.dfs.GetRequest
	(*GetResponse)(nil),    // 9: dfs.dfs.GetResponse
	(*PutRequest)(nil),     // 10: dfs.dfs.PutRequest
	(*PutResponse)(nil),    // 11: dfs.dfs.PutResponse
	(*DeleteRequest)(nil),  // 12: dfs.dfs.DeleteRequest
	(*DeleteResponse)(nil), // 13: dfs.dfs.DeleteResponse
}
var file_proto_DfsService_proto_depIdxs = []int32{
	0,  // 0: dfs.dfs.DfsService.stop:input_type -> dfs.dfs.StopRequest
	2,  // 1: dfs.dfs.DfsService.dir:input_type -> dfs.dfs.DirRequest
	4,  // 2: dfs.dfs.DfsService.mkdir:input_type -> dfs.dfs.MkdirRequest
	6,  // 3: dfs.dfs.DfsService.rmdir:input_type -> dfs.dfs.RmdirRequest
	8,  // 4: dfs.dfs.DfsService.get:input_type -> dfs.dfs.GetRequest
	10, // 5: dfs.dfs.DfsService.put:input_type -> dfs.dfs.PutRequest
	12, // 6: dfs.dfs.DfsService.delete:input_type -> dfs.dfs.DeleteRequest
	1,  // 7: dfs.dfs.DfsService.stop:output_type -> dfs.dfs.StopResponse
	3,  // 8: dfs.dfs.DfsService.dir:output_type -> dfs.dfs.DirResponse
	5,  // 9: dfs.dfs.DfsService.mkdir:output_type -> dfs.dfs.MkdirResponse
	7,  // 10: dfs.dfs.DfsService.rmdir:output_type -> dfs.dfs.RmdirResponse
	9,  // 11: dfs.dfs.DfsService.get:output_type -> dfs.dfs.GetResponse
	11, // 12: dfs.dfs.DfsService.put:output_type -> dfs.dfs.PutResponse
	13, // 13: dfs.dfs.DfsService.delete:output_type -> dfs.dfs.DeleteResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_DfsService_proto_init() }
func file_proto_DfsService_proto_init() {
	if File_proto_DfsService_proto != nil {
		return
	}
	file_proto_DfsService_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_DfsService_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_DfsService_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_DfsService_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_DfsService_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_DfsService_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_DfsService_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_DfsService_proto_rawDesc), len(file_proto_DfsService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_DfsService_proto_goTypes,
		DependencyIndexes: file_proto_DfsService_proto_depIdxs,
		MessageInfos:      file_proto_DfsService_proto_msgTypes,
	}.Build()
	File_proto_DfsService_proto = out.File
	file_proto_DfsService_proto_goTypes = nil
	file_proto_DfsService_proto_depIdxs = nil
}
