// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/ExtentService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_ExtentService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ExtentService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_ExtentService_proto_rawDescGZIP(), []int{0}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_ExtentService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ExtentService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_ExtentService_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_ExtentService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ExtentService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ExtentService_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=fileData,proto3,oneof" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_ExtentService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ExtentService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ExtentService_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=fileData,proto3,oneof" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_ExtentService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ExtentService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_ExtentService_proto_rawDescGZIP(), []int{4}
}

func (x *PutRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PutRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_ExtentService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ExtentService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_ExtentService_proto_rawDescGZIP(), []int{5}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

var File_proto_ExtentService_proto protoreflect.FileDescriptor

const file_proto_ExtentService_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ExtentService.proto\x12\n" +
	"dfs.extent\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"(\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\";\n" +
	"\vGetResponse\x12\x1f\n" +
	"\bfileData\x18\x01 \x01(\fH\x00R\bfileData\x88\x01\x01B\v\n" +
	"\t_fileData\"V\n" +
	"\n" +
	"PutRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\bfileData\x18\x02 \x01(\fH\x00R\bfileData\x88\x01\x01B\v\n" +
	"\t_fileData\"8\n" +
	"\vPutResponse\x12\x1d\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x88\x01\x01B\n" +
	"\n" +
	"\b_success2\xba\x01\n" +
	"\rExtentService\x129\n" +
	"\x04stop\x12\x17.dfs.extent.StopRequest\x1a\x18.dfs.extent.StopResponse\x126\n" +
	"\x03get\x12\x16.dfs.extent.GetRequest\x1a\x17.dfs.extent.GetResponse\x126\n" +
	"\x03put\x12\x16.dfs.extent.PutRequest\x1a\x17.dfs.extent.PutResponseb\x06proto3"

var (
	file_proto_ExtentService_proto_rawDescOnce sync.Once
	file_proto_ExtentService_proto_rawDescData []byte
)

func file_proto_ExtentService_proto_rawDescGZIP() []byte {
	file_proto_ExtentService_proto_rawDescOnce.Do(func() {
		file_proto_ExtentService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ExtentService_proto_rawDesc), len(file_proto_ExtentService_proto_rawDesc)))
	})
	return file_proto_ExtentService_proto_rawDescData
}

var file_proto_ExtentService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ExtentService_proto_goTypes = []any{
	(*StopRequest)(nil),  // 0: dfs.extent.StopRequest
	(*StopResponse)(nil), // 1: dfs.extent.StopResponse
	(*GetRequest)(nil),   // 2: dfs.extent.GetRequest
	(*GetResponse)(nil),  // 3: dfs.extent.GetResponse
	(*PutRequest)(nil),   // 4: dfs.extent.PutRequest
	(*PutResponse)(nil),  // 5: dfs.extent.PutResponse
}
var file_proto_ExtentService_proto_depIdxs = []int32{
	0, // 0: dfs.extent.ExtentService.stop:input_type -> dfs.extent.StopRequest
	2, // 1: dfs.extent.ExtentService.get:input_type -> dfs.extent.GetRequest
	4, // 2: dfs.extent.ExtentService.put:input_type -> dfs.extent.PutRequest
	1, // 3: dfs.extent.ExtentService.stop:output_type -> dfs.extent.StopResponse
	3, // 4: dfs.extent.ExtentService.get:output_type -> dfs.extent.GetResponse
	5, // 5: dfs.extent.ExtentService.put:output_type -> dfs.extent.PutResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ExtentService_proto_init() }
func file_proto_ExtentService_proto_init() {
	if File_proto_ExtentService_proto != nil {
		return
	}
	file_proto_ExtentService_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_ExtentService_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_ExtentService_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ExtentService_proto_rawDesc), len(file_proto_ExtentService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ExtentService_proto_goTypes,
		DependencyIndexes: file_proto_ExtentService_proto_depIdxs,
		MessageInfos:      file_proto_ExtentService_proto_msgTypes,
	}.Build()
	File_proto_ExtentService_proto = out.File
	file_proto_ExtentService_proto_goTypes = nil
	file_proto_ExtentService_proto_depIdxs = nil
}
