// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/extent.proto

package extent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_extent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_extent_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_proto_extent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_proto_extent_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_extent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_extent_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PutRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_proto_extent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_proto_extent_proto_rawDescGZIP(), []int{3}
}

func (x *PutReply) GetResult() *wrapperspb.BoolValue {
	if x != nil {
		return x.Result
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_extent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_extent_proto_rawDescGZIP(), []int{4}
}

type StopReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReply) Reset() {
	*x = StopReply{}
	mi := &file_proto_extent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReply) ProtoMessage() {}

func (x *StopReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReply.ProtoReflect.Descriptor instead.
func (*StopReply) Descriptor() ([]byte, []int) {
	return file_proto_extent_proto_rawDescGZIP(), []int{5}
}

func (x *StopReply) GetResult() *wrapperspb.BoolValue {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_extent_proto protoreflect.FileDescriptor

const file_proto_extent_proto_rawDesc = "" +
	"\n" +
	"\x12proto/extent.proto\x12\x06extent\x1a\x1egoogle/protobuf/wrappers.proto\"(\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\"\x1e\n" +
	"\bGetReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"<\n" +
	"\n" +
	"PutRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\">\n" +
	"\bPutReply\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x06result\"\r\n" +
	"\vStopRequest\"?\n" +
	"\tStopReply\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x06result2\x92\x01\n" +
	"\x06Extent\x12+\n" +
	"\x03Get\x12\x12.extent.GetRequest\x1a\x10.extent.GetReply\x12+\n" +
	"\x03Put\x12\x12.extent.PutRequest\x1a\x10.extent.PutReply\x12.\n" +
	"\x04Stop\x12\x13.extent.StopRequest\x1a\x11.extent.StopReplyB\x19Z\x17proto-gen/extent;extentb\x06proto3"

var (
	file_proto_extent_proto_rawDescOnce sync.Once
	file_proto_extent_proto_rawDescData []byte
)

func file_proto_extent_proto_rawDescGZIP() []byte {
	file_proto_extent_proto_rawDescOnce.Do(func() {
		file_proto_extent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_extent_proto_rawDesc), len(file_proto_extent_proto_rawDesc)))
	})
	return file_proto_extent_proto_rawDescData
}

var file_proto_extent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_extent_proto_goTypes = []any{
	(*GetRequest)(nil),           // 0: extent.GetRequest
	(*GetReply)(nil),             // 1: extent.GetReply
	(*PutRequest)(nil),           // 2: extent.PutRequest
	(*PutReply)(nil),             // 3: extent.PutReply
	(*StopRequest)(nil),          // 4: extent.StopRequest
	(*StopReply)(nil),            // 5: extent.StopReply
	(*wrapperspb.BoolValue)(nil), // 6: google.protobuf.BoolValue
}
var file_proto_extent_proto_depIdxs = []int32{
	6, // 0: extent.PutReply.result:type_name -> google.protobuf.BoolValue
	6, // 1: extent.StopReply.result:type_name -> google.protobuf.BoolValue
	0, // 2: extent.Extent.Get:input_type -> extent.GetRequest
	2, // 3: extent.Extent.Put:input_type -> extent.PutRequest
	4, // 4: extent.Extent.Stop:input_type -> extent.StopRequest
	1, // 5: extent.Extent.Get:output_type -> extent.GetReply
	3, // 6: extent.Extent.Put:output_type -> extent.PutReply
	5, // 7: extent.Extent.Stop:output_type -> extent.StopReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_extent_proto_init() }
func file_proto_extent_proto_init() {
	if File_proto_extent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_extent_proto_rawDesc), len(file_proto_extent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_extent_proto_goTypes,
		DependencyIndexes: file_proto_extent_proto_depIdxs,
		MessageInfos:      file_proto_extent_proto_msgTypes,
	}.Build()
	File_proto_extent_proto = out.File
	file_proto_extent_proto_goTypes = nil
	file_proto_extent_proto_depIdxs = nil
}
