// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/ReplicaService.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicaService_Stop_FullMethodName               = "/dfs.replica.ReplicaService/stop"
	ReplicaService_GetView_FullMethodName            = "/dfs.replica.ReplicaService/getView"
	ReplicaService_ExecuteMethod_FullMethodName      = "/dfs.replica.ReplicaService/executeMethod"
	ReplicaService_GetExecutedMethods_FullMethodName = "/dfs.replica.ReplicaService/getExecutedMethods"
	ReplicaService_IsRecovered_FullMethodName        = "/dfs.replica.ReplicaService/isRecovered"
)

// ReplicaServiceClient is the client API for ReplicaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicaServiceClient interface {
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*GetViewResponse, error)
	ExecuteMethod(ctx context.Context, in *ExecuteMethodRequest, opts ...grpc.CallOption) (*ExecuteMethodResponse, error)
	GetExecutedMethods(ctx context.Context, in *GetExecutedMethodsRequest, opts ...grpc.CallOption) (*GetExecutedMethodsResponse, error)
	IsRecovered(ctx context.Context, in *IsRecoveredRequest, opts ...grpc.CallOption) (*IsRecoveredResponse, error)
}

type replicaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaServiceClient(cc grpc.ClientConnInterface) ReplicaServiceClient {
	return &replicaServiceClient{cc}
}

func (c *replicaServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, ReplicaService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*GetViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetViewResponse)
	err := c.cc.Invoke(ctx, ReplicaService_GetView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ExecuteMethod(ctx context.Context, in *ExecuteMethodRequest, opts ...grpc.CallOption) (*ExecuteMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteMethodResponse)
	err := c.cc.Invoke(ctx, ReplicaService_ExecuteMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) GetExecutedMethods(ctx context.Context, in *GetExecutedMethodsRequest, opts ...grpc.CallOption) (*GetExecutedMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutedMethodsResponse)
	err := c.cc.Invoke(ctx, ReplicaService_GetExecutedMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) IsRecovered(ctx context.Context, in *IsRecoveredRequest, opts ...grpc.CallOption) (*IsRecoveredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsRecoveredResponse)
	err := c.cc.Invoke(ctx, ReplicaService_IsRecovered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaServiceServer is the server API for ReplicaService service.
// All implementations must embed UnimplementedReplicaServiceServer
// for forward compatibility.
type ReplicaServiceServer interface {
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	GetView(context.Context, *GetViewRequest) (*GetViewResponse, error)
	ExecuteMethod(context.Context, *ExecuteMethodRequest) (*ExecuteMethodResponse, error)
	GetExecutedMethods(context.Context, *GetExecutedMethodsRequest) (*GetExecutedMethodsResponse, error)
	IsRecovered(context.Context, *IsRecoveredRequest) (*IsRecoveredResponse, error)
	mustEmbedUnimplementedReplicaServiceServer()
}

// UnimplementedReplicaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicaServiceServer struct{}

func (UnimplementedReplicaServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedReplicaServiceServer) GetView(context.Context, *GetViewRequest) (*GetViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetView not implemented")
}
func (UnimplementedReplicaServiceServer) ExecuteMethod(context.Context, *ExecuteMethodRequest) (*ExecuteMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteMethod not implemented")
}
func (UnimplementedReplicaServiceServer) GetExecutedMethods(context.Context, *GetExecutedMethodsRequest) (*GetExecutedMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutedMethods not implemented")
}
func (UnimplementedReplicaServiceServer) IsRecovered(context.Context, *IsRecoveredRequest) (*IsRecoveredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsRecovered not implemented")
}
func (UnimplementedReplicaServiceServer) mustEmbedUnimplementedReplicaServiceServer() {}
func (UnimplementedReplicaServiceServer) testEmbeddedByValue()                        {}

// UnsafeReplicaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaServiceServer will
// result in compilation errors.
type UnsafeReplicaServiceServer interface {
	mustEmbedUnimplementedReplicaServiceServer()
}

func RegisterReplicaServiceServer(s grpc.ServiceRegistrar, srv ReplicaServiceServer) {
	// If the following call pancis, it indicates UnimplementedReplicaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicaService_ServiceDesc, srv)
}

func _ReplicaService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_GetView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ExecuteMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ExecuteMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_ExecuteMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ExecuteMethod(ctx, req.(*ExecuteMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_GetExecutedMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutedMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).GetExecutedMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_GetExecutedMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).GetExecutedMethods(ctx, req.(*GetExecutedMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_IsRecovered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsRecoveredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).IsRecovered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_IsRecovered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).IsRecovered(ctx, req.(*IsRecoveredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaService_ServiceDesc is the grpc.ServiceDesc for ReplicaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.replica.ReplicaService",
	HandlerType: (*ReplicaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "stop",
			Handler:    _ReplicaService_Stop_Handler,
		},
		{
			MethodName: "getView",
			Handler:    _ReplicaService_GetView_Handler,
		},
		{
			MethodName: "executeMethod",
			Handler:    _ReplicaService_ExecuteMethod_Handler,
		},
		{
			MethodName: "getExecutedMethods",
			Handler:    _ReplicaService_GetExecutedMethods_Handler,
		},
		{
			MethodName: "isRecovered",
			Handler:    _ReplicaService_IsRecovered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ReplicaService.proto",
}
