// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/ReplicaService.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_ReplicaService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{0}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_ReplicaService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{1}
}

type GetViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewRequest) Reset() {
	*x = GetViewRequest{}
	mi := &file_proto_ReplicaService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewRequest) ProtoMessage() {}

func (x *GetViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewRequest.ProtoReflect.Descriptor instead.
func (*GetViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{2}
}

type GetViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        int64                  `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	View          []string               `protobuf:"bytes,2,rep,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewResponse) Reset() {
	*x = GetViewResponse{}
	mi := &file_proto_ReplicaService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewResponse) ProtoMessage() {}

func (x *GetViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewResponse.ProtoReflect.Descriptor instead.
func (*GetViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{3}
}

func (x *GetViewResponse) GetViewId() int64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *GetViewResponse) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

type ExecuteMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodRequest *MethodRequest         `protobuf:"bytes,1,opt,name=methodRequest,proto3" json:"methodRequest,omitempty"`
	Viewstamp     *Viewstamp             `protobuf:"bytes,2,opt,name=viewstamp,proto3" json:"viewstamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMethodRequest) Reset() {
	*x = ExecuteMethodRequest{}
	mi := &file_proto_ReplicaService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMethodRequest) ProtoMessage() {}

func (x *ExecuteMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMethodRequest.ProtoReflect.Descriptor instead.
func (*ExecuteMethodRequest) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteMethodRequest) GetMethodRequest() *MethodRequest {
	if x != nil {
		return x.MethodRequest
	}
	return nil
}

func (x *ExecuteMethodRequest) GetViewstamp() *Viewstamp {
	if x != nil {
		return x.Viewstamp
	}
	return nil
}

type ExecuteMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrimary     bool                   `protobuf:"varint,1,opt,name=isPrimary,proto3" json:"isPrimary,omitempty"`
	ReturnValue   *string                `protobuf:"bytes,2,opt,name=returnValue,proto3,oneof" json:"returnValue,omitempty"` // Value is serialized JSON object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMethodResponse) Reset() {
	*x = ExecuteMethodResponse{}
	mi := &file_proto_ReplicaService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMethodResponse) ProtoMessage() {}

func (x *ExecuteMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMethodResponse.ProtoReflect.Descriptor instead.
func (*ExecuteMethodResponse) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteMethodResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ExecuteMethodResponse) GetReturnValue() string {
	if x != nil && x.ReturnValue != nil {
		return *x.ReturnValue
	}
	return ""
}

type MethodRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MethodName       string                 `protobuf:"bytes,1,opt,name=methodName,proto3" json:"methodName,omitempty"`
	MethodParameters []string               `protobuf:"bytes,2,rep,name=methodParameters,proto3" json:"methodParameters,omitempty"` // Each method parameter is serialized JSON object
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MethodRequest) Reset() {
	*x = MethodRequest{}
	mi := &file_proto_ReplicaService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodRequest) ProtoMessage() {}

func (x *MethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodRequest.ProtoReflect.Descriptor instead.
func (*MethodRequest) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{6}
}

func (x *MethodRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *MethodRequest) GetMethodParameters() []string {
	if x != nil {
		return x.MethodParameters
	}
	return nil
}

type Viewstamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        int64                  `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Viewstamp) Reset() {
	*x = Viewstamp{}
	mi := &file_proto_ReplicaService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewstamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewstamp) ProtoMessage() {}

func (x *Viewstamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewstamp.ProtoReflect.Descriptor instead.
func (*Viewstamp) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{7}
}

func (x *Viewstamp) GetViewId() int64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *Viewstamp) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetExecutedMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutedMethodsRequest) Reset() {
	*x = GetExecutedMethodsRequest{}
	mi := &file_proto_ReplicaService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutedMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutedMethodsRequest) ProtoMessage() {}

func (x *GetExecutedMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutedMethodsRequest.ProtoReflect.Descriptor instead.
func (*GetExecutedMethodsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{8}
}

type GetExecutedMethodsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MethodRequests []*MethodRequest       `protobuf:"bytes,1,rep,name=methodRequests,proto3" json:"methodRequests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetExecutedMethodsResponse) Reset() {
	*x = GetExecutedMethodsResponse{}
	mi := &file_proto_ReplicaService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutedMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutedMethodsResponse) ProtoMessage() {}

func (x *GetExecutedMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutedMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetExecutedMethodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{9}
}

func (x *GetExecutedMethodsResponse) GetMethodRequests() []*MethodRequest {
	if x != nil {
		return x.MethodRequests
	}
	return nil
}

type IsRecoveredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsRecoveredRequest) Reset() {
	*x = IsRecoveredRequest{}
	mi := &file_proto_ReplicaService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRecoveredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRecoveredRequest) ProtoMessage() {}

func (x *IsRecoveredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRecoveredRequest.ProtoReflect.Descriptor instead.
func (*IsRecoveredRequest) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{10}
}

type IsRecoveredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRecovered   bool                   `protobuf:"varint,1,opt,name=isRecovered,proto3" json:"isRecovered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsRecoveredResponse) Reset() {
	*x = IsRecoveredResponse{}
	mi := &file_proto_ReplicaService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRecoveredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRecoveredResponse) ProtoMessage() {}

func (x *IsRecoveredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ReplicaService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRecoveredResponse.ProtoReflect.Descriptor instead.
func (*IsRecoveredResponse) Descriptor() ([]byte, []int) {
	return file_proto_ReplicaService_proto_rawDescGZIP(), []int{11}
}

func (x *IsRecoveredResponse) GetIsRecovered() bool {
	if x != nil {
		return x.IsRecovered
	}
	return false
}

var File_proto_ReplicaService_proto protoreflect.FileDescriptor

const file_proto_ReplicaService_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/ReplicaService.proto\x12\vdfs.replica\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"\x10\n" +
	"\x0eGetViewRequest\"=\n" +
	"\x0fGetViewResponse\x12\x16\n" +
	"\x06viewId\x18\x01 \x01(\x03R\x06viewId\x12\x12\n" +
	"\x04view\x18\x02 \x03(\tR\x04view\"\x8e\x01\n" +
	"\x14ExecuteMethodRequest\x12@\n" +
	"\rmethodRequest\x18\x01 \x01(\v2\x1a.dfs.replica.MethodRequestR\rmethodRequest\x124\n" +
	"\tviewstamp\x18\x02 \x01(\v2\x16.dfs.replica.ViewstampR\tviewstamp\"l\n" +
	"\x15ExecuteMethodResponse\x12\x1c\n" +
	"\tisPrimary\x18\x01 \x01(\bR\tisPrimary\x12%\n" +
	"\vreturnValue\x18\x02 \x01(\tH\x00R\vreturnValue\x88\x01\x01B\x0e\n" +
	"\f_returnValue\"[\n" +
	"\rMethodRequest\x12\x1e\n" +
	"\n" +
	"methodName\x18\x01 \x01(\tR\n" +
	"methodName\x12*\n" +
	"\x10methodParameters\x18\x02 \x03(\tR\x10methodParameters\"?\n" +
	"\tViewstamp\x12\x16\n" +
	"\x06viewId\x18\x01 \x01(\x03R\x06viewId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\"\x1b\n" +
	"\x19GetExecutedMethodsRequest\"`\n" +
	"\x1aGetExecutedMethodsResponse\x12B\n" +
	"\x0emethodRequests\x18\x01 \x03(\v2\x1a.dfs.replica.MethodRequestR\x0emethodRequests\"\x14\n" +
	"\x12IsRecoveredRequest\"7\n" +
	"\x13IsRecoveredResponse\x12 \n" +
	"\visRecovered\x18\x01 \x01(\bR\visRecovered2\xa4\x03\n" +
	"\x0eReplicaService\x12;\n" +
	"\x04stop\x12\x18.dfs.replica.StopRequest\x1a\x19.dfs.replica.StopResponse\x12D\n" +
	"\agetView\x12\x1b.dfs.replica.GetViewRequest\x1a\x1c.dfs.replica.GetViewResponse\x12V\n" +
	"\rexecuteMethod\x12!.dfs.replica.ExecuteMethodRequest\x1a\".dfs.replica.ExecuteMethodResponse\x12e\n" +
	"\x12getExecutedMethods\x12&.dfs.replica.GetExecutedMethodsRequest\x1a'.dfs.replica.GetExecutedMethodsResponse\x12P\n" +
	"\visRecovered\x12\x1f.dfs.replica.IsRecoveredRequest\x1a .dfs.replica.IsRecoveredResponseb\x06proto3"

var (
	file_proto_ReplicaService_proto_rawDescOnce sync.Once
	file_proto_ReplicaService_proto_rawDescData []byte
)

func file_proto_ReplicaService_proto_rawDescGZIP() []byte {
	file_proto_ReplicaService_proto_rawDescOnce.Do(func() {
		file_proto_ReplicaService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ReplicaService_proto_rawDesc), len(file_proto_ReplicaService_proto_rawDesc)))
	})
	return file_proto_ReplicaService_proto_rawDescData
}

var file_proto_ReplicaService_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_ReplicaService_proto_goTypes = []any{
	(*StopRequest)(nil),                // 0: dfs.replica.StopRequest
	(*StopResponse)(nil),               // 1: dfs.replica.StopResponse
	(*GetViewRequest)(nil),             // 2: dfs.replica.GetViewRequest
	(*GetViewResponse)(nil),            // 3: dfs.replica.GetViewResponse
	(*ExecuteMethodRequest)(nil),       // 4: dfs.replica.ExecuteMethodRequest
	(*ExecuteMethodResponse)(nil),      // 5: dfs.replica.ExecuteMethodResponse
	(*MethodRequest)(nil),              // 6: dfs.replica.MethodRequest
	(*Viewstamp)(nil),                  // 7: dfs.replica.Viewstamp
	(*GetExecutedMethodsRequest)(nil),  // 8: dfs.replica.GetExecutedMethodsRequest
	(*GetExecutedMethodsResponse)(nil), // 9: dfs.replica.GetExecutedMethodsResponse
	(*IsRecoveredRequest)(nil),         // 10: dfs.replica.IsRecoveredRequest
	(*IsRecoveredResponse)(nil),        // 11: dfs.replica.IsRecoveredResponse
}
var file_proto_ReplicaService_proto_depIdxs = []int32{
	6,  // 0: dfs.replica.ExecuteMethodRequest.methodRequest:type_name -> dfs.replica.MethodRequest
	7,  // 1: dfs.replica.ExecuteMethodRequest.viewstamp:type_name -> dfs.replica.Viewstamp
	6,  // 2: dfs.replica.GetExecutedMethodsResponse.methodRequests:type_name -> dfs.replica.MethodRequest
	0,  // 3: dfs.replica.ReplicaService.stop:input_type -> dfs.replica.StopRequest
	2,  // 4: dfs.replica.ReplicaService.getView:input_type -> dfs.replica.GetViewRequest
	4,  // 5: dfs.replica.ReplicaService.executeMethod:input_type -> dfs.replica.ExecuteMethodRequest
	8,  // 6: dfs.replica.ReplicaService.getExecutedMethods:input_type -> dfs.replica.GetExecutedMethodsRequest
	10, // 7: dfs.replica.ReplicaService.isRecovered:input_type -> dfs.replica.IsRecoveredRequest
	1,  // 8: dfs.replica.ReplicaService.stop:output_type -> dfs.replica.StopResponse
	3,  // 9: dfs.replica.ReplicaService.getView:output_type -> dfs.replica.GetViewResponse
	5,  // 10: dfs.replica.ReplicaService.executeMethod:output_type -> dfs.replica.ExecuteMethodResponse
	9,  // 11: dfs.replica.ReplicaService.getExecutedMethods:output_type -> dfs.replica.GetExecutedMethodsResponse
	11, // 12: dfs.replica.ReplicaService.isRecovered:output_type -> dfs.replica.IsRecoveredResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ReplicaService_proto_init() }
func file_proto_ReplicaService_proto_init() {
	if File_proto_ReplicaService_proto != nil {
		return
	}
	file_proto_ReplicaService_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ReplicaService_proto_rawDesc), len(file_proto_ReplicaService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ReplicaService_proto_goTypes,
		DependencyIndexes: file_proto_ReplicaService_proto_depIdxs,
		MessageInfos:      file_proto_ReplicaService_proto_msgTypes,
	}.Build()
	File_proto_ReplicaService_proto = out.File
	file_proto_ReplicaService_proto_goTypes = nil
	file_proto_ReplicaService_proto_depIdxs = nil
}
